spring.application.name=cost
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/fraisdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=kimi7
jwt.secret=5359ba6c-0562-4e30-8f15-5aca75fb5376


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
